Repository HYF-Class19/practice-code-review-group3, pull requests merged in 2022-11, with the labels that each got.

#7 Deep flat
  .DS_Store
  .cspell.json
  package-lock.json
  src/deep-flat/README.md
  src/deep-flat/deep-flat.js
  src/deep-flat/deep-flat.spec.js
Labels: exercise 1

#10 Difference
  src/difference/difference.js
  src/difference/difference.spec.js
Labels: difference

#13 Split object solved
  README.md
  package-lock.json
  package.json
  src/split-object/README.md
  src/split-object/split-object.js
  src/split-object/split-object.spec.js
Labels: exercise 4
